// ─── PPL Exercise Database ───────────────────────────────────────────────────

export interface ExerciseSpec {
  name: string;
  emoji: string;
  sets: number;
  repRange: string;
  rest: string;
  tip: string;
  targetMuscle: string;
}

export interface SessionSpec {
  key: string;
  name: string;
  fullName: string;
  emoji: string;
  color: string;
  tagline: string;
  muscles: string;
  exercises: ExerciseSpec[];
  warmup: string[];
  cooldown: string[];
}

// Day-of-week index → session key
export const DOW_TO_SESSION: Record<number, string> = {
  0: 'mobility', // Sunday
  1: 'pushA',    // Monday
  2: 'pullA',    // Tuesday
  3: 'legsA',    // Wednesday
  4: 'pushB',    // Thursday
  5: 'pullB',    // Friday
  6: 'legsB',    // Saturday
};

export const SESSIONS: Record<string, SessionSpec> = {
  pushA: {
    key: 'pushA',
    name: 'Push A',
    fullName: 'Push Day A — Chest Focus',
    emoji: '💪',
    color: '#FF6B35',
    tagline: 'Build that chest. Make it heavy.',
    muscles: 'Chest · Front Delts · Triceps',
    warmup: ['5 min arm circles & band pull-aparts', '2 sets push-ups × 15 (bodyweight)', 'Shoulder rotation stretches'],
    cooldown: ['Doorway chest stretch × 30s each side', 'Tricep overhead stretch × 20s', 'Cross-body shoulder stretch'],
    exercises: [
      {
        name: 'Flat Barbell Bench Press',
        emoji: '🏋️',
        sets: 4,
        repRange: '8–10',
        rest: '2–3 min',
        tip: 'Retract scapula, feet flat on floor. Drive the bar, don\'t just push.',
        targetMuscle: 'Chest',
      },
      {
        name: 'Incline Dumbbell Press',
        emoji: '↗️',
        sets: 3,
        repRange: '10–12',
        rest: '90s',
        tip: 'Set bench at 30-45°. Control the eccentric — 2 seconds down.',
        targetMuscle: 'Upper Chest',
      },
      {
        name: 'Chest Push-ups (weighted / elevated)',
        emoji: '🤜',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Add a plate on your back or use an elevated surface for extra resistance. Keep elbows at 45° to protect shoulders.',
        targetMuscle: 'Chest (inner & lower)',
      },
      {
        name: 'Military Press (Seated)',
        emoji: '🎖️',
        sets: 3,
        repRange: '8–10',
        rest: '90s',
        tip: 'Keep core braced. Don\'t arch your lower back excessively.',
        targetMuscle: 'Front Delts',
      },
      {
        name: 'Lateral Raises',
        emoji: '🦅',
        sets: 4,
        repRange: '15–20',
        rest: '45s',
        tip: 'Lead with your elbows, not your hands. Slight lean forward.',
        targetMuscle: 'Side Delts',
      },
      {
        name: 'Tricep Rope Pushdowns',
        emoji: '🪝',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Flare the rope at the bottom. Keep elbows pinned to your sides.',
        targetMuscle: 'Triceps (lateral head)',
      },
      {
        name: 'Overhead Tricep Extension',
        emoji: '⬆️',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Full stretch at the bottom. Keep elbows close to your head.',
        targetMuscle: 'Triceps (long head)',
      },
    ],
  },

  pullA: {
    key: 'pullA',
    name: 'Pull A',
    fullName: 'Pull Day A — Deadlift Focus',
    emoji: '🏋️',
    color: '#4ECDC4',
    tagline: 'Pull heavy. Build your back.',
    muscles: 'Back · Rear Delts · Biceps',
    warmup: ['Cat-cow × 10 reps', 'Band pull-aparts × 20', 'Hip hinge with dowel rod × 10'],
    cooldown: ['Child\'s pose × 45s', 'Lat stretch doorway × 30s each', 'Bicep wall stretch × 20s'],
    exercises: [
      {
        name: 'Conventional Deadlift',
        emoji: '💀',
        sets: 4,
        repRange: '5–6',
        rest: '3 min',
        tip: 'Bar over mid-foot, lats tight, drive the floor away. Reset each rep.',
        targetMuscle: 'Full posterior chain',
      },
      {
        name: 'Barbell Bent-Over Row',
        emoji: '🔩',
        sets: 4,
        repRange: '8–10',
        rest: '90s',
        tip: 'Torso at 45°. Row to your lower chest. Squeeze the back, don\'t just pull.',
        targetMuscle: 'Mid Back, Lats',
      },
      {
        name: 'Lat Pulldown (wide grip)',
        emoji: '📐',
        sets: 3,
        repRange: '10–12',
        rest: '75s',
        tip: 'Slight arch, pull the bar to your upper chest. Drive elbows to pockets.',
        targetMuscle: 'Lats',
      },
      {
        name: 'Seated Cable Row',
        emoji: '🚣',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Chest tall, drive elbows back past your body. 1-second hold at peak.',
        targetMuscle: 'Mid Back, Rhomboids',
      },
      {
        name: 'Reverse Curl (Forearm & Bicep)',
        emoji: '💪',
        sets: 3,
        repRange: '12–15',
        rest: '45s',
        tip: 'Overhand grip on the bar. Keep wrists straight and elbows pinned. Builds forearm thickness and brachialis.',
        targetMuscle: 'Forearms, Brachialis, Biceps',
      },
      {
        name: 'Barbell Bicep Curl',
        emoji: '💈',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Don\'t swing. Full range — stretch at bottom, squeeze at top.',
        targetMuscle: 'Biceps',
      },
      {
        name: 'Hammer Curl',
        emoji: '🔨',
        sets: 3,
        repRange: '12–15',
        rest: '45s',
        tip: 'Neutral grip. Works brachialis for bigger overall arm peak.',
        targetMuscle: 'Brachialis, Biceps',
      },
    ],
  },

  legsA: {
    key: 'legsA',
    name: 'Legs A',
    fullName: 'Legs Day A — Quad Dominant',
    emoji: '🦵',
    color: '#FFE66D',
    tagline: 'No skipping. Champions train legs.',
    muscles: 'Quads · Hamstrings · Calves · Glutes',
    warmup: ['Bodyweight squats × 15', 'Hip circles × 10 each direction', 'Walking lunges × 10 steps'],
    cooldown: ['Pigeon pose × 45s each side', 'Standing quad stretch × 20s', 'Calf wall stretch × 30s'],
    exercises: [
      {
        name: 'Back Squat',
        emoji: '👑',
        sets: 4,
        repRange: '8–10',
        rest: '3 min',
        tip: 'Break parallel. Knees track over toes. Brace your core before every rep.',
        targetMuscle: 'Quads, Glutes',
      },
      {
        name: 'Romanian Deadlift (RDL)',
        emoji: '🦩',
        sets: 3,
        repRange: '10–12',
        rest: '90s',
        tip: 'Hinge at hips, slight knee bend. Feel the hamstring stretch. Bar stays close.',
        targetMuscle: 'Hamstrings, Glutes',
      },
      {
        name: 'Leg Extension',
        emoji: '📏',
        sets: 3,
        repRange: '15–20',
        rest: '60s',
        tip: 'Pause 1s at the top. Focus on VMO (inner quad) engagement.',
        targetMuscle: 'Quads (isolation)',
      },
      {
        name: 'Lying Leg Curl',
        emoji: '🌀',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Control the eccentric. Don\'t let the weight crash down.',
        targetMuscle: 'Hamstrings (isolation)',
      },
      {
        name: 'Standing Calf Raises',
        emoji: '👟',
        sets: 4,
        repRange: '15–25',
        rest: '45s',
        tip: 'Full range — deep stretch at bottom. Pause 1s at top. Slow and controlled.',
        targetMuscle: 'Gastrocnemius',
      },
      {
        name: 'Hip Thrust',
        emoji: '🍑',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Drive through heels. Full hip extension at the top. Glute squeeze!',
        targetMuscle: 'Glutes',
      },
    ],
  },

  pushB: {
    key: 'pushB',
    name: 'Push B',
    fullName: 'Push Day B — Shoulder Focus',
    emoji: '💪',
    color: '#FF6B35',
    tagline: 'Shoulder day. Build those boulders.',
    muscles: 'Shoulders · Upper Chest · Triceps',
    warmup: ['Band pull-aparts × 20', 'Shoulder CARs × 5 each arm', '2 sets push-ups × 12'],
    cooldown: ['Chest doorway stretch × 30s', 'Sleeper stretch × 20s each', 'Tricep overhead stretch × 20s'],
    exercises: [
      {
        name: 'Incline Barbell Bench Press',
        emoji: '↗️',
        sets: 4,
        repRange: '8–10',
        rest: '2–3 min',
        tip: '30–45° incline. Full stretch at bottom. Retract scapula throughout.',
        targetMuscle: 'Upper Chest',
      },
      {
        name: 'Military Press (Standing)',
        emoji: '🏋️',
        sets: 3,
        repRange: '10–12',
        rest: '90s',
        tip: 'Stand with toes together and brace your core hard, then press overhead. Keeping toes together eliminates leg drive and forces strict shoulder work.',
        targetMuscle: 'Front & Side Delts',
      },
      {
        name: 'Arnold Press',
        emoji: '🏆',
        sets: 3,
        repRange: '10–12',
        rest: '90s',
        tip: 'Rotate from palms-facing-you to palms-forward as you press up. Controlled.',
        targetMuscle: 'All 3 Delt Heads',
      },
      {
        name: 'Lateral Raises',
        emoji: '🔗',
        sets: 4,
        repRange: '15–20',
        rest: '45s',
        tip: 'Lead with your elbows, not your hands. Slight lean forward. Pinch at the top.',
        targetMuscle: 'Side Delts',
      },
      {
        name: 'Front Shoulder Raises',
        emoji: '⬆️',
        sets: 3,
        repRange: '12–15',
        rest: '45s',
        tip: 'Alternate arms or both together. Keep a slight bend in the elbow. Raise to eye level — don\'t shrug.',
        targetMuscle: 'Front Delts',
      },
      {
        name: 'Pec Deck / Dumbbell Fly',
        emoji: '🦋',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Slight elbow bend, squeeze for 1s at the peak contraction. Use pec deck machine or dumbbells on flat bench.',
        targetMuscle: 'Chest (inner)',
      },
      {
        name: 'Tricep Pulldown (rope or bar)',
        emoji: '🪝',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Keep elbows pinned to your sides. Fully extend at the bottom — flare the rope out. Focus on the squeeze.',
        targetMuscle: 'Triceps (lateral head)',
      },
      {
        name: 'Tricep Dips (weighted)',
        emoji: '⬇️',
        sets: 3,
        repRange: '10–12',
        rest: '75s',
        tip: 'Slight forward lean for chest. Upright for pure tricep focus.',
        targetMuscle: 'Triceps',
      },
      {
        name: 'Diamond Push-ups',
        emoji: '💎',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Hands in diamond under chest. Keep core tight. Burn out finisher.',
        targetMuscle: 'Triceps, Inner Chest',
      },
    ],
  },

  pullB: {
    key: 'pullB',
    name: 'Pull B',
    fullName: 'Pull Day B — Row Focus',
    emoji: '🏋️',
    color: '#4ECDC4',
    tagline: 'Row everything. Build a thick back.',
    muscles: 'Back (rows) · Rear Delts · Bicep Variations',
    warmup: ['Band pull-aparts × 20', 'Scapular pull-ups × 10', 'Cat-cow × 10'],
    cooldown: ['Child\'s pose × 45s', 'Bicep doorway stretch × 20s each', 'Thoracic spine rotations × 5 each'],
    exercises: [
      {
        name: 'Dead Hang',
        emoji: '🧲',
        sets: 4,
        repRange: '20–45s hold',
        rest: '90s',
        tip: 'Full dead hang from a pull-up bar. Relax your shoulders and feel the lats stretch. Build grip and scapular strength — foundation for pull-ups.',
        targetMuscle: 'Lats, Grip, Scapula',
      },
      {
        name: 'Machine Row (or Chest-Supported Row)',
        emoji: '✝️',
        sets: 4,
        repRange: '10–12',
        rest: '90s',
        tip: 'Drive elbows back and squeeze rhomboids at the peak. Chest-supported takes the lower back out of it.',
        targetMuscle: 'Mid Back, Thickness',
      },
      {
        name: 'Single-Arm DB Row',
        emoji: '🦾',
        sets: 3,
        repRange: '12 each',
        rest: '60s',
        tip: 'Brace on bench. Drive elbow to ceiling. Full stretch at the bottom.',
        targetMuscle: 'Lats, Mid Back',
      },
      {
        name: 'Straight-Arm Pulldown',
        emoji: '⬇️',
        sets: 3,
        repRange: '15–20',
        rest: '45s',
        tip: 'Arms stay straight (slight elbow bend). Pure lat isolation. Go light.',
        targetMuscle: 'Lats (isolation)',
      },
      {
        name: 'Rear Delt Dumbbell Fly (bent over)',
        emoji: '🦅',
        sets: 3,
        repRange: '15–20',
        rest: '45s',
        tip: 'Bend forward 90°, arms hanging. Raise dumbbells to sides keeping elbows slightly bent. Focus on rear delts, not traps.',
        targetMuscle: 'Rear Delts',
      },
      {
        name: 'Concentration Curl',
        emoji: '🙏',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Sit on a bench, elbow on inner thigh. Curl up slowly and squeeze hard at the top. Perfect bicep peak isolation without any machine.',
        targetMuscle: 'Biceps (peak)',
      },
      {
        name: 'Dumbbell Curl (both arms)',
        emoji: '🔁',
        sets: 3,
        repRange: '12–15',
        rest: '45s',
        tip: 'Supinate (rotate) your wrist as you curl up for full bicep activation. Don\'t let elbows drift forward.',
        targetMuscle: 'Biceps',
      },
    ],
  },

  legsB: {
    key: 'legsB',
    name: 'Legs B',
    fullName: 'Legs Day B — Posterior Chain',
    emoji: '🦵',
    color: '#FFE66D',
    tagline: 'Hamstrings & glutes. Go deep.',
    muscles: 'Hamstrings · Glutes · Calves (seated)',
    warmup: ['Glute bridges × 15', 'Nordic curl negatives × 5', 'Hip flexor stretch × 30s each'],
    cooldown: ['Pigeon pose × 60s each', 'Standing hamstring stretch × 30s', 'Hip flexor lunge stretch × 30s'],
    exercises: [
      {
        name: 'Romanian Deadlift (heavy)',
        emoji: '💀',
        sets: 4,
        repRange: '8–10',
        rest: '2–3 min',
        tip: 'This is the main lift today. Go heavier than Legs A. Maximum hamstring stretch.',
        targetMuscle: 'Hamstrings, Glutes',
      },
      {
        name: 'Bulgarian Split Squat',
        emoji: '🇧🇬',
        sets: 3,
        repRange: '10 each leg',
        rest: '90s',
        tip: 'Rear foot elevated on bench. Drive through front heel. Brutal but effective.',
        targetMuscle: 'Quads, Glutes (unilateral)',
      },
      {
        name: 'Lying Leg Curl (slow)',
        emoji: '🐌',
        sets: 4,
        repRange: '12–15',
        rest: '60s',
        tip: '3-second eccentric. Pause 1s at peak. Hamstring torture. Worth it.',
        targetMuscle: 'Hamstrings (isolation)',
      },
      {
        name: 'Good Mornings',
        emoji: '🌅',
        sets: 3,
        repRange: '10–12',
        rest: '75s',
        tip: 'Bar on upper traps, hinge at hips. Maintain neutral spine throughout.',
        targetMuscle: 'Hamstrings, Lower Back',
      },
      {
        name: 'Walking Lunges',
        emoji: '🚶',
        sets: 3,
        repRange: '12 steps each leg',
        rest: '60s',
        tip: 'Long stride. Front knee over toe. Drive through front heel to stand.',
        targetMuscle: 'Quads, Glutes (unilateral)',
      },
      {
        name: 'Seated Calf Raise',
        emoji: '💺',
        sets: 4,
        repRange: '15–25',
        rest: '30s',
        tip: 'Seated targets soleus (often neglected). Full stretch at bottom. Slow.',
        targetMuscle: 'Soleus, Calves',
      },
      {
        name: 'Cable Glute Kickback',
        emoji: '🦶',
        sets: 3,
        repRange: '15 each leg',
        rest: '30s',
        tip: 'Keep hip square. Drive through heel. Squeeze glute at peak.',
        targetMuscle: 'Glutes (isolation)',
      },
    ],
  },

  mobility: {
    key: 'mobility',
    name: 'Mobility',
    fullName: 'Active Recovery & Mobility',
    emoji: '🧘',
    color: '#A78BFA',
    tagline: 'Rest is training. Recover like a pro.',
    muscles: 'Full body flexibility & joint health',
    warmup: ['5 min light cardio (walk or cycle)', '3 deep breaths in child\'s pose'],
    cooldown: ['10 min progressive muscle relaxation', 'Journalling: how does your body feel?'],
    exercises: [
      {
        name: 'Hip Flexor Lunge Stretch',
        emoji: '🦵',
        sets: 3,
        repRange: '45s each side',
        rest: '15s',
        tip: 'Tuck your pelvis under. Feel the front of your hip opening up.',
        targetMuscle: 'Hip Flexors',
      },
      {
        name: 'Thoracic Spine Rotation',
        emoji: '🌀',
        sets: 3,
        repRange: '10 each side',
        rest: '10s',
        tip: 'In quadruped position. Keep lower back still. Rotate from mid-back.',
        targetMuscle: 'Thoracic Spine',
      },
      {
        name: 'Cat-Cow Flow',
        emoji: '🐱',
        sets: 3,
        repRange: '10 slow reps',
        rest: '10s',
        tip: 'Inhale for cow (arch), exhale for cat (round). Move every vertebra.',
        targetMuscle: 'Spine, Core',
      },
      {
        name: 'Doorway Chest Stretch',
        emoji: '🚪',
        sets: 2,
        repRange: '45s each arm',
        rest: '10s',
        tip: 'Forearm on doorframe at 90°. Gentle lean forward. Don\'t overstretch.',
        targetMuscle: 'Pecs, Biceps',
      },
      {
        name: 'Pigeon Pose (Hip Opener)',
        emoji: '🕊️',
        sets: 2,
        repRange: '60s each side',
        rest: '10s',
        tip: 'Flex front foot for knee protection. Breathe into the hip.',
        targetMuscle: 'Piriformis, Glutes',
      },
      {
        name: 'World\'s Greatest Stretch',
        emoji: '🌍',
        sets: 2,
        repRange: '5 each side',
        rest: '15s',
        tip: 'Lunge, drop elbow to floor, rotate arm to sky. Best full-body stretch.',
        targetMuscle: 'Full Body',
      },
      {
        name: 'Foam Roll (full body)',
        emoji: '🧴',
        sets: 1,
        repRange: '60–90s per area',
        rest: '0',
        tip: 'Pause on tender spots (trigger points) for 20–30s. Don\'t rush this.',
        targetMuscle: 'Fascia & Muscles',
      },
    ],
  },
};


