
export interface ExerciseSpec {
  name: string;
  emoji: string;
  sets: number;
  repRange: string;
  rest: string;
  tip: string;
  targetMuscle: string;
  isCompound?: boolean;
  isBigFinish?: boolean;
  isBurnout?: boolean;
  isCircuit?: boolean;
}

export interface SessionSpec {
  key: string;
  name: string;
  fullName: string;
  emoji: string;
  color: string;
  tagline: string;
  muscles: string;
  exercises: ExerciseSpec[];
  warmup: string[];
  cooldown: string[];
}

// Day-of-week index → session key
export const DOW_TO_SESSION: Record<number, string> = {
  0: 'mobility', // Sunday
  1: 'pushA',    // Monday
  2: 'pullA',    // Tuesday
  3: 'legsA',    // Wednesday
  4: 'pushB',    // Thursday
  5: 'pullB',    // Friday
  6: 'legsB',    // Saturday
};

export const SESSIONS: Record<string, SessionSpec> = {
  pushA: {
    key: 'pushA',
    name: 'Push A',
    fullName: 'Push Day A — Upper Chest Focus',
    emoji: '💪',
    color: '#FF6B35',
    tagline: 'Upper chest, front delts, triceps long head. Go heavy.',
    muscles: 'Upper Chest · Front Delts · Triceps (long head)',
    warmup: ['5 min arm circles & band pull-aparts', '2 sets push-ups x 15 (bodyweight)', 'Shoulder rotation stretches'],
    cooldown: ['Doorway chest stretch x 30s each side', 'Tricep overhead stretch x 20s', 'Cross-body shoulder stretch'],
    exercises: [
      {
        name: 'Incline Barbell Bench Press',
        emoji: '🏋️',
        sets: 4,
        repRange: '8–6',
        rest: '3–5 min',
        tip: 'Heavy and flat — main chest builder, creates the filled-out look. Retract scapula, feet flat, drive the bar.',
        targetMuscle: 'Upper Chest',
        isCompound: true,
      },
      {
        name: 'Low Cable Fly (upward)',
        emoji: '↗️',
        sets: 3,
        repRange: '12–15',
        rest: '60s',
        tip: 'Cable at lowest position, pull upward and across — directly targets upper chest fibers.',
        targetMuscle: 'Upper Chest (inner)',
      },
      {
        name: 'Seated Dumbbell Shoulder Press',
        emoji: '🎖️',
        sets: 3,
        repRange: '8–10',
        rest: '60s',
        tip: 'Core braced. Don\'t arch your lower back excessively. Control the eccentric.',
        targetMuscle: 'Front Delts',
      },
      {
        name: 'Lateral Raises',
        emoji: '🦅',
        sets: 3,
        repRange: '15–20',
        rest: '45s',
        tip: 'Slight forward lean, thumb down pinky up at top — maximum side delt activation.',
        targetMuscle: 'Side Delts',
      },
      {
        name: 'Overhead Tricep Extension (cable or dumbbell)',
        emoji: '⬆️',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Arm overhead = long head fully stretched = most growth stimulus. Full stretch at bottom.',
        targetMuscle: 'Triceps (long head)',
        isBigFinish: true,
      },
      {
        name: 'Tricep Rope Pushdowns',
        emoji: '🪝',
        sets: 3,
        repRange: '15–15',
        rest: '60s',
        tip: 'Flare the rope at bottom. Keep elbows pinned. Constant tension for lateral head volume.',
        targetMuscle: 'Triceps (lateral head)',
      },
    ],
  },

  pullA: {
    key: 'pullA',
    name: 'Pull A',
    fullName: 'Pull Day A — Deadlift Focus',
    emoji: '🏋️',
    color: '#4ECDC4',
    tagline: 'Back, rear delts, biceps — stretch priority.',
    muscles: 'Back · Rear Delts · Biceps (stretch priority)',
    warmup: ['Cat-cow x 10 reps', 'Band pull-aparts x 20', 'Hip hinge with dowel rod x 10'],
    cooldown: ['Child\'s pose x 45s', 'Lat stretch doorway x 30s each', 'Bicep wall stretch x 20s'],
    exercises: [
      {
        name: 'Conventional Deadlift',
        emoji: '💀',
        sets: 4,
        repRange: '5–6',
        rest: '3 min',
        tip: 'Bar over mid-foot, lats tight, drive the floor away. Reset each rep.',
        targetMuscle: 'Full posterior chain',
        isCompound: true,
      },
      {
        name: 'Barbell Bent-Over Row',
        emoji: '🔩',
        sets: 4,
        repRange: '8–10',
        rest: '60s',
        tip: 'Torso at 45°. Row to your lower chest. Squeeze the back, don\'t just pull.',
        targetMuscle: 'Mid Back, Lats',
      },
      {
        name: 'Lat Pulldown (wide grip)',
        emoji: '📐',
        sets: 3,
        repRange: '10–12',
        rest: '75s',
        tip: 'Slight arch, pull the bar to your upper chest. Drive elbows to pockets.',
        targetMuscle: 'Lats',
      },
      {
        name: 'Incline Dumbbell Curl',
        emoji: '💪',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Arm hangs fully behind body — best single exercise for bicep peak. Stretch priority.',
        targetMuscle: 'Biceps (stretch focus)',
      },
      {
        name: 'Barbell Curl (close grip)',
        emoji: '💈',
        sets: 3,
        repRange: '10–15',
        rest: '60s',
        tip: 'Don\'t swing. Full range — stretch at bottom, squeeze at top.',
        targetMuscle: 'Biceps (inner)',
      },
      {
        name: 'Reverse Curl',
        emoji: '🔨',
        sets: 3,
        repRange: '12–15',
        rest: '45s',
        tip: 'Overhand grip, wrists straight, elbows pinned. Builds forearm thickness and brachialis.',
        targetMuscle: 'Brachialis, Forearms',
      },
      {
        name: '21s (Barbell Curl)',
        emoji: '🔥',
        sets: 1,
        repRange: '7 bottom + 7 top + 7 full',
        rest: '30s',
        tip: 'Lighter weight — burnout finisher, not a strength movement. Pump and feel the burn.',
        targetMuscle: 'Biceps',
        isBurnout: true,
      },
    ],
  },

  legsA: {
    key: 'legsA',
    name: 'Legs A',
    fullName: 'Legs Day A — Quad + Abs',
    emoji: '🦵',
    color: '#FFE66D',
    tagline: 'Quads, hamstrings, calves, glutes, core. No skipping.',
    muscles: 'Quads · Hamstrings · Calves · Glutes · Core',
    warmup: ['Bodyweight squats x 15', 'Hip circles x 10 each direction', 'Walking lunges x 10 steps'],
    cooldown: ['Pigeon pose x 45s each side', 'Standing quad stretch x 20s', 'Calf wall stretch x 30s'],
    exercises: [
      {
        name: 'Back Squat',
        emoji: '👑',
        sets: 4,
        repRange: '8–10',
        rest: '3–5 min',
        tip: 'Break parallel. Knees track over toes. Brace your core before every rep.',
        targetMuscle: 'Quads, Glutes',
        isCompound: true,
      },
      {
        name: 'Romanian Deadlift (RDL)',
        emoji: '🦩',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Hinge at hips, slight knee bend. Feel the hamstring stretch. Bar stays close.',
        targetMuscle: 'Hamstrings, Glutes',
      },
      {
        name: 'Lying Leg Curl',
        emoji: '🌀',
        sets: 4,
        repRange: '12–15',
        rest: '60s',
        tip: 'Control the eccentric. Don\'t let the weight crash down.',
        targetMuscle: 'Hamstrings (isolation)',
      },
      {
        name: 'Standing Calf Raises',
        emoji: '👟',
        sets: 3,
        repRange: '15–25',
        rest: '45s',
        tip: 'Full range — deep stretch at bottom. Pause 1s at top. Slow and controlled.',
        targetMuscle: 'Gastrocnemius',
      },
      {
        name: 'Hip Thrust',
        emoji: '🍑',
        sets: 3,
        repRange: '12',
        rest: '60s',
        tip: 'Drive through heels. Full hip extension at the top. Glute squeeze!',
        targetMuscle: 'Glutes',
      },
      {
        name: 'Plank Hold',
        emoji: '🧱',
        sets: 3,
        repRange: '45–60s hold',
        rest: '20s',
        tip: 'Always first in abs circuit — activates deep core before dynamic movements. Lower back flat.',
        targetMuscle: 'Deep core',
        isCircuit: true,
      },
      {
        name: 'V-Ups / Tuck Crunches',
        emoji: '🔻',
        sets: 3,
        repRange: '15',
        rest: '30s',
        tip: 'Both ends meet in the middle — full ab contraction. Upper + lower abs simultaneously.',
        targetMuscle: 'Upper + Lower Abs',
        isCircuit: true,
      },
      {
        name: 'Reverse Crunches',
        emoji: '🔄',
        sets: 3,
        repRange: '15',
        rest: '30s',
        tip: 'Curl hips off the floor at the top — this is what makes it work. Control the movement.',
        targetMuscle: 'Lower Abs',
        isCircuit: true,
      },
    ],
  },

  pushB: {
    key: 'pushB',
    name: 'Push B',
    fullName: 'Push Day B — Shoulder + Flat Chest',
    emoji: '💪',
    color: '#FF6B35',
    tagline: 'Shoulders, full chest, triceps lateral head.',
    muscles: 'Shoulders · Full Chest · Triceps (lateral head)',
    warmup: ['Band pull-aparts x 20', 'Shoulder CARs x 5 each arm', '2 sets push-ups x 12'],
    cooldown: ['Chest doorway stretch x 30s', 'Sleeper stretch x 20s each', 'Tricep overhead stretch x 20s'],
    exercises: [
      {
        name: 'Flat Barbell Bench Press',
        emoji: '🏋️',
        sets: 4,
        repRange: '8–10',
        rest: '3–5 min',
        tip: 'Retract scapula, feet flat. Drive the bar — main chest mass builder.',
        targetMuscle: 'Full Chest',
        isCompound: true,
      },
      {
        name: 'Pec Deck / Cable Fly',
        emoji: '🦋',
        sets: 3,
        repRange: '10–15',
        rest: '60s',
        tip: 'Slight elbow bend, squeeze for 1s at the peak contraction. Pure inner chest isolation.',
        targetMuscle: 'Chest (inner)',
      },
      {
        name: 'Standing Military Press',
        emoji: '🎖️',
        sets: 3,
        repRange: '10–15',
        rest: '60s',
        tip: 'Toes together, brace core hard. Eliminates leg drive — forces strict shoulder work.',
        targetMuscle: 'Front & Side Delts',
      },
      {
        name: 'Lateral Raises (cable or dumbbell)',
        emoji: '🦅',
        sets: 3,
        repRange: '15–20',
        rest: '45s',
        tip: 'Lead with elbows, slight forward lean. Pinch at the top for maximum delt activation.',
        targetMuscle: 'Side Delts',
      },
      {
        name: 'Skull Crushers / Close Grip Bench',
        emoji: '💎',
        sets: 3,
        repRange: '10–12',
        rest: '60s',
        tip: 'Build arm thickness — most important triceps exercise most people skip. 1.5 rep style for extra tension.',
        targetMuscle: 'Triceps (long head)',
        isBigFinish: true,
      },
      {
        name: 'Cable Tricep Pushdown',
        emoji: '🪝',
        sets: 3,
        repRange: '15–15',
        rest: '60s',
        tip: 'Constant cable tension — maximum long head volume. Keep elbows pinned, full extension.',
        targetMuscle: 'Triceps (lateral head)',
      },
    ],
  },

  pullB: {
    key: 'pullB',
    name: 'Pull B',
    fullName: 'Pull Day B — Row Focus',
    emoji: '🏋️',
    color: '#4ECDC4',
    tagline: 'Back rows, rear delts, biceps peak contraction.',
    muscles: 'Back (rows) · Rear Delts · Biceps (peak contraction)',
    warmup: ['Band pull-aparts x 20', 'Scapular pull-ups x 10', 'Cat-cow x 10'],
    cooldown: ['Child\'s pose x 45s', 'Bicep doorway stretch x 20s each', 'Thoracic spine rotations x 5 each'],
    exercises: [
      {
        name: 'Dead Hang',
        emoji: '🧲',
        sets: 2,
        repRange: '10–20s hold',
        rest: '90s',
        tip: 'Full dead hang. Relax shoulders, feel lats stretch. Decompression + grip work.',
        targetMuscle: 'Decompression, Grip',
      },
      {
        name: 'Chest-Supported Row / Machine Row',
        emoji: '✝️',
        sets: 3,
        repRange: '12 each',
        rest: '60s',
        tip: 'Drive elbows back and squeeze rhomboids at peak. Chest-supported removes lower back strain.',
        targetMuscle: 'Back',
      },
      {
        name: 'Rear Delt Fly (bent over or cable)',
        emoji: '🦅',
        sets: 3,
        repRange: '10–20',
        rest: '45s',
        tip: 'Bend forward 90°, raise to sides. Focus on rear delts, not traps.',
        targetMuscle: 'Rear Delts',
      },
      {
        name: '21s (EZ Bar or Dumbbell Curl)',
        emoji: '🔥',
        sets: 2,
        repRange: '7 bottom + 7 top + 7 full',
        rest: '60s',
        tip: 'Lighter weight — full range breakdown, huge pump. Peak contraction focus.',
        targetMuscle: 'Biceps',
        isBurnout: true,
      },
      {
        name: 'Concentration Curl / Spider Curl',
        emoji: '🙏',
        sets: 3,
        repRange: '12',
        rest: '60s',
        tip: 'Put supination hold at the top every rep. Short head emphasis — builds bicep peak.',
        targetMuscle: 'Biceps (short head)',
      },
      {
        name: 'Hammer Curl (cross body or standard)',
        emoji: '🔨',
        sets: 3,
        repRange: '12–15 each',
        rest: '45s',
        tip: 'Neutral grip. Works brachialis and inner arm for bigger overall arm thickness.',
        targetMuscle: 'Brachialis, Inner arm',
      },
    ],
  },

  legsB: {
    key: 'legsB',
    name: 'Legs B',
    fullName: 'Legs Day B — Posterior Chain + Abs',
    emoji: '🦵',
    color: '#FFE66D',
    tagline: 'Hamstrings, glutes, calves, core. Go deep.',
    muscles: 'Hamstrings · Glutes · Calves · Core',
    warmup: ['Glute bridges x 15', 'Nordic curl negatives x 5', 'Hip flexor stretch x 30s each'],
    cooldown: ['Pigeon pose x 60s each', 'Standing hamstring stretch x 30s', 'Hip flexor lunge stretch x 30s'],
    exercises: [
      {
        name: 'Romanian Deadlift (heavy)',
        emoji: '💀',
        sets: 4,
        repRange: '8–10',
        rest: '5–8 min',
        tip: 'This is the main lift today. Go heavier than Legs A. Maximum hamstring stretch.',
        targetMuscle: 'Hamstrings, Glutes',
        isCompound: true,
      },
      {
        name: 'Bulgarian Split Squat',
        emoji: '🇧🇬',
        sets: 3,
        repRange: '10 each leg',
        rest: '90s',
        tip: 'Rear foot elevated on bench. Drive through front heel. Brutal but effective.',
        targetMuscle: 'Quads, Glutes (unilateral)',
      },
      {
        name: 'Lying Leg Curl (slow)',
        emoji: '🐌',
        sets: 4,
        repRange: '12–15',
        rest: '60s',
        tip: '3-second eccentric. Pause 1s at peak. Hamstring isolation with slow tempo.',
        targetMuscle: 'Hamstrings (isolation)',
      },
      {
        name: 'Seated Calf Raise',
        emoji: '💺',
        sets: 4,
        repRange: '15–20',
        rest: '30s',
        tip: 'Seated targets soleus (often neglected). Full stretch at bottom. Slow and controlled.',
        targetMuscle: 'Soleus, Calves',
      },
      {
        name: 'Plank Hold',
        emoji: '🧱',
        sets: 3,
        repRange: '45–60s hold',
        rest: '20s',
        tip: 'Lower back flat, glutes squeezed — don\'t let hips sag. Deep core activation.',
        targetMuscle: 'Deep core',
        isCircuit: true,
      },
      {
        name: 'Reverse Crunches',
        emoji: '🔄',
        sets: 3,
        repRange: '12–15',
        rest: '30s',
        tip: 'Curl hips off the floor at the top. Focus on lower ab contraction.',
        targetMuscle: 'Lower Abs',
        isCircuit: true,
      },
      {
        name: 'Cable Crunches / Weighted Crunches',
        emoji: '🔥',
        sets: 3,
        repRange: '15–20',
        rest: '30s',
        tip: 'Upper abs burnout finisher. Squeeze hard at peak contraction.',
        targetMuscle: 'Upper Abs (burnout)',
        isCircuit: true,
      },
    ],
  },

  mobility: {
    key: 'mobility',
    name: 'Mobility',
    fullName: 'Active Recovery & Mobility',
    emoji: '🧘',
    color: '#A78BFA',
    tagline: 'Full body flexibility & joint health. Rest is training.',
    muscles: 'Full Body Flexibility · Joint Health',
    warmup: ['5 min light cardio (walk or cycle)', '3 deep breaths in child\'s pose'],
    cooldown: ['10 min progressive muscle relaxation', 'Journalling: how does your body feel?'],
    exercises: [
      {
        name: 'Hip Flexor Lunge Stretch',
        emoji: '🦵',
        sets: 3,
        repRange: '45s each side',
        rest: '10s',
        tip: 'Tuck your pelvis under. Feel the front of your hip opening up.',
        targetMuscle: 'Hip Flexors',
      },
      {
        name: 'Thoracic Spine Rotation',
        emoji: '🌀',
        sets: 3,
        repRange: '12 each side',
        rest: '15s',
        tip: 'In quadruped position. Keep lower back still. Rotate from mid-back.',
        targetMuscle: 'Thoracic Spine',
      },
      {
        name: 'Cat-Cow Flow',
        emoji: '🐱',
        sets: 3,
        repRange: '10 slow reps',
        rest: '0',
        tip: 'Inhale for cow (arch), exhale for cat (round). Move every vertebra.',
        targetMuscle: 'Spine, Core',
      },
      {
        name: 'Doorway Chest Stretch',
        emoji: '🚪',
        sets: 3,
        repRange: '45s each arm',
        rest: '15s',
        tip: 'Forearm on doorframe at 90°. Gentle lean forward. Opens pecs and ribcage.',
        targetMuscle: 'Pecs, Ribcage',
      },
      {
        name: 'Pigeon Pose (Hip Opener)',
        emoji: '🕊️',
        sets: 3,
        repRange: '60s hold',
        rest: '10s',
        tip: 'Flex front foot for knee protection. Breathe into the hip.',
        targetMuscle: 'Piriformis, Glutes',
      },
      {
        name: 'World\'s Greatest Stretch',
        emoji: '🌍',
        sets: 2,
        repRange: '5 each side',
        rest: '15s',
        tip: 'Lunge, drop elbow to floor, rotate arm to sky. Best full-body stretch.',
        targetMuscle: 'Full Body',
      },
      {
        name: 'Foam Roll (full body)',
        emoji: '🧴',
        sets: 1,
        repRange: '40–60s per area',
        rest: '0',
        tip: 'Pause on tender spots (trigger points) for 20-30s. Don\'t rush this. Fascia release.',
        targetMuscle: 'Fascia & Muscles',
      },
    ],
  },
};
